forky:
  replicas: 1

  image:
    repository: ethpandaops/forky
    tag: 0.0.31-debian

  resources:
    requests:
      cpu: 256m
      memory: 512Mi

  extraVolumes:
  - name: forky-data
    resource:
      requests:
        storage: 50Gi
  
  extraVolumeMounts:
  - name: forky-data
    mountPath: /data

  ingress:
    enabled: true

    className: ingress-nginx-public

    hosts:
      - host: forky.testing-devnet.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix
  serviceMonitor:
    enabled: true
    labels:
      vmagent: common
  config:
    listen_addr: ":5555"
    pprof_addr: ":6060"
    log_level: "info"
    metrics:
      addr: ":9090"
      enabled: true

    http:
      edge_cache:
        enabled: true

        frame_ttl: 1440m

    forky:
      retention_period: "8760h"

      store:
        type: fs
        config:
          path: "/data/forky/payloads"

      indexer:
        dsn: /data/forky/indexer.db
        driver_name: sqlite

      sources:
      - name: "prysm-geth-001"
        type: "beacon_node"
        config:
          address: "http://prysm-geth-001:5052"
          polling_interval: "4s"
      
      ethereum:
        network:
          name: "testing-devnet"
          spec:
            seconds_per_slot: 12
            slots_per_epoch: 32
            genesis_time: 1684234860
