default_ethereum_client_images:
  geth: ethereum/client-go:v1.11.6
  lighthouse: michaelsproul/lighthouse:test

lighthouse_container_command_extra_args:
  - --testnet-dir=/network-config
  - --boot-nodes={{ ethereum_cl_bootnodes | join(',') }}
  - --debug-level=debug
  - --shuffling-cache-size=256