node-001:
  global:
    main:
      network: testing-devnet
      engineEndpoint: http://{{ .Release.Name }}-execution:8551
      rpcEndpoint: http://{{ .Release.Name }}-execution:8545
      beaconEndpoint: http://{{ .Release.Name }}-beacon:5052
    checkpointSync:
      enabled: false
  #Geth
  geth:
    fullnameOverride: geth-prysm-001
    enabled: true
    image:
      repository: ethereum/client-go
      tag: v1.11.6
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 50Gi
    podLabels:
      network: testing-devnet
      testnet: testing-devnet
      ethereum_network: testing-devnet
      ethereum_role: execution
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: geth-prysm-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    extraArgs:
      - --bootnodes="$(tr '\n' ',' < /data/bootnodes.txt)"
      - --networkid="$(cat /data/chainid.txt)"
      - --ws.api="eth,net,engine,web3,txpool"
      - --http.api="eth,net,engine,web3,txpool"
      - --ethstats=rpc-geth-prysm:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.testing-devnets.ethstats_secret}>@ethstats.testing-devnet.ethpandaops.io
      - --syncmode=full
      - --gcmode archive
    initContainers:
    - name: init-genesis
      image: ethereum/client-go:v1.11.6
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          BOOTNODE_URI=https://config.testing-devnet.ethpandaops.io/el/bootnodes;
          GENESIS_URI=https://config.testing-devnet.ethpandaops.io/el/genesis.json;
          if ! [ -f /data/genesis_init_done ];
          then
            wget -O /data/genesis.json $GENESIS_URI;
            wget -O /data/bootnodes.txt $BOOTNODE_URI;
            apk update && apk add jq;
            cat /data/genesis.json | jq -r '.config.chainId' > /data/chainid.txt;
            geth init --datadir /data /data/genesis.json;
            touch /data/genesis_init_done;
            echo "genesis init done";
          else
            echo "genesis is already initialized";
          fi;
          echo "bootnode init done: $(cat /data/bootnodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
  # Prysm
  prysm:
    fullnameOverride: prysm-geth-001
    enabled: true
    image:
      repository: ethpandaops/prysm
      tag: v4.0.3
      pullPolicy: Always
    mode: "beacon"
    podLabels:
      network: testing-devnet
      testnet: testing-devnet
      ethereum_network: testing-devnet
      ethereum_role: consensus
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: geth-prysm-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 50Gi
    extraArgs:
      - --execution-endpoint=http://geth-prysm-001:8551
      - "--bootstrap-node=enr:-Iq4QAOpZmhjlNufctu7sIoUbYBzHf6DbPNmVzM6arvqdEHuIJ6ju7MIFaAlBgAn4rW3gw1jMhIS6SlK9DIXIMJT-f-GAYgV9zPLgmlkgnY0gmlwhK6KC66Jc2VjcDI1NmsxoQNRVLSWkLN2QD2hJV-h9QjBGzhJiypTTVBm5iInoVPC0IN1ZHCCIyk"
      - "--bootstrap-node=enr:-Iq4QJEhqdQZafLjLVMJqGFJlIlJBn1x3K03hQL4qBYGybTrOITDVvzuCWz33wU7fFZhxb4OtFeUr8hnzhw2GAWPbd2GAYgV95augmlkgnY0gmlwhKdjOiGJc2VjcDI1NmsxoQJ-pwNcIfru4tfsxS35E34y60lkS4VbjyucluzkMzC6vYN1ZHCCIyk"
      - "--bootstrap-node=enr:-Iq4QFUDGkvvO4_UJN0ljGydFBF1vVA-fcauG5K52S-XBYPAd7CULCwudDAUFPT5yxbwcbzRnbFsa4aAiQ2WPBxp-6CGAYgV96VqgmlkgnY0gmlwhI5d0pyJc2VjcDI1NmsxoQIWRSUju4ohEFH4bhyMZ-aHRxzYNv-BjBnPQREYZKBTlIN1ZHCCIyk"
      - "--bootstrap-node=enr:-Ly4QNkqKrDOxzZhTKB1hEpPGmFo4Qbc2G5zxDi-GasLnwKtbsig609BpmDNDUZLm3zeSw5NhmpebkGacWxfQhCHvYABh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCUNM6OQAAARRQAAAAAAAAAgmlkgnY0gmlwhK6KC66Jc2VjcDI1NmsxoQJKZrdm_em6lRxRp4OgYEdNbEv4Cwi1eJUrB6zQUYydbIhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"
      - "--bootstrap-node=enr:-Ly4QOAjwQrmvz9e3-jHooNL3RZ7edhOe3nms4QrwQccb6lweNaTLoy9r879ShqMbIEKoFl8Kgcwu6H-8CBnm5cdV-4Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCUNM6OQAAARRQAAAAAAAAAgmlkgnY0gmlwhKdjOiGJc2VjcDI1NmsxoQLe-X-GPhJGWsBijNEOicnnJv6W_X_NTTEcAwXSKJLkIYhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"
      - "--bootstrap-node=enr:-Ly4QL8juPSkM5rAxHR4XIBI20cVy94I3QgW54pH9B_ewaZVPnDdczmGlZg7KlcjuKhOb0K_NzknESm_saoyjSTSVggBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCUNM6OQAAARRQAAAAAAAAAgmlkgnY0gmlwhI5d0pyJc2VjcDI1NmsxoQNA0VNSUxZ3h_D4AhjPjXocRnLqrmA-p9Fnp6m0V3oJRohzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"
      - --genesis-state=/data/testnet_spec/genesis.ssz
      - --chain-config-file=/data/testnet_spec/config.yaml
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -acex
        - >
          DEPOSIT_CONTRACT_URI="https://config.testing-devnet.ethpandaops.io/deposit_contract.txt";
          DEPOSIT_CONTRACT_BLOCK_URI="https://config.testing-devnet.ethpandaops.io/cl/deposit_contract_block.txt";
          DEPLOY_BLOCK_URI="https://config.testing-devnet.ethpandaops.io/cl/deploy_block.txt";
          GENESIS_CONFIG_URI="https://config.testing-devnet.ethpandaops.io/cl/config.yaml";
          GENESIS_SSZ_URI="https://config.testing-devnet.ethpandaops.io/cl/genesis.ssz";
          BOOTNODE_URI="https://config.testing-devnet.ethpandaops.io/bootstrap_nodes.txt";
          mkdir -p /data/testnet_spec;
          if ! [ -f /data/testnet_spec/genesis.ssz ];
          then
            wget -O /data/testnet_spec/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/testnet_spec/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/testnet_spec/deploy_block.txt $DEPLOY_BLOCK_URI;
            wget -O /data/testnet_spec/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/testnet_spec/genesis.ssz $GENESIS_SSZ_URI;
            wget -O /data/testnet_spec/bootstrap_nodes.txt $BOOTNODE_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          echo "bootnode init done: $(cat /data/testnet_spec/bootstrap_nodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
