# Find All + Replace all instances of these values in this entire folder to swap to a different network
network: testing-devnet
chainId: 4844001005

# Actual values (change these too)
domain: testing-devnet.ethpandaops.io

## Config controls the files that are served by the `config.` subdomain.
config:
  enabled: true

  files:
    # Support all files as they appear in the github repo
    - path: /besu.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/besu.json
    - path: /boot_enr.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/boot_enr.txt
    - path: /bootstrap_nodes.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/bootstrap_nodes.txt
    - path: /chainspec.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/chainspec.json
    - path: /config.yaml
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/config.yaml
    - path: /deploy_block.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/deploy_block.txt
    - path: /deposit_contract.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/deposit_contract.txt
    - path: /deposit_contract_block.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/deposit_contract_block.txt
    - path: /deposit_contract_block_hash.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/deposit_contract_block_hash.txt
    - path: /genesis.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/genesis.json
    - path: /genesis.ssz
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/genesis.ssz
    - path: /parseBeaconState.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/parseBeaconState.json

    # Execution Layer specific redirects
    - path: /el/bootnodes
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/bootnode.txt
    - path: /el/besu.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/besu.json
    - path: /el/chainspec.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/chainspec.json
    - path: /el/genesis.json
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/genesis.json

    # Consensus Layer specific redirects
    - path: /cl/bootnodes
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/bootstrap_nodes.txt
    - path: /cl/config.yaml
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/config.yaml
    - path: /cl/genesis.ssz
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/genesis.ssz
    - path: /cl/deploy_block.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/deploy_block.txt
    - path: /cl/deposit_contract.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/deposit_contract.txt
    - path: /cl/deposit_contract_block.txt
      upstream: raw.githubusercontent.com
      target: /ethpandaops/testing-devnet/master/network-configs/testing-devnet/deposit_contract_block.txt

    # Ansible generated ethereum nodes inventory
    - path: /api/v1/nodes/inventory
      upstream: bootnode-1.srv.testing-devnet.ethpandaops.io
      target: /meta/api/v1/inventory.json
