- name: Check if rsync is installed
  ansible.builtin.package:
    name: rsync
    state: present

- name: Check if dir exists
  ansible.builtin.stat:
    path: "{{ validator_keys_sync_files[0].dest }}"
  register: validataor_keys_dir_0

- name: Copy key directories
  when: not validataor_keys_dir_0.stat.exists
  block:
    - name: Create dest dir
      ansible.builtin.file:
        path: "{{ item.dest | dirname }}"
        state: directory
        recurse: true
      loop: "{{ validator_keys_sync_files }}"
    - name: Copy keys
      ansible.posix.synchronize:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop: "{{ validator_keys_sync_files }}"
