- name: Check if rsync is installed
  ansible.builtin.package:
    name: rsync
    state: present

- name: Create dest dir
  ansible.builtin.file:
    path: "{{ eth_testnet_config_dir }}"
    state: directory
    recurse: true

- name: Copy local config dir
  ansible.posix.synchronize:
    src: "{{ eth_testnet_config_local_dir_src }}"
    dest: "{{ eth_testnet_config_dir }}/"
