- name: Check if git is installed
  ansible.builtin.package:
    name: git
    state: present

- name: Create dest dir
  ansible.builtin.file:
    path: "{{ eth_testnet_config_dir }}"
    state: directory
    recurse: true

- name: Create temporary git checkout dir
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: eth_testnet_config_git_temp_dir

- name: Git checkout config
  ansible.builtin.git:
    repo: "{{ eth_testnet_config_git_repo }}"
    dest: "{{ eth_testnet_config_git_temp_dir.path }}"
    version: "{{ eth_testnet_config_git_version }}"
    depth: 1

- name: Copy config directory
  ansible.builtin.copy:
    src: "{{ eth_testnet_config_git_temp_dir.path }}/{{eth_testnet_config_git_sub_dir}}/"
    dest: "{{ eth_testnet_config_dir }}/"
    remote_src: yes

- name: Remove temp dir
  ansible.builtin.file:
    path: "{{ eth_testnet_config_git_temp_dir.path }}"
    state: absent
