#
# Copy over custom network config directory
#
- name: Check if config dir exists
  ansible.builtin.stat:
    path: "{{ eth_testnet_config_dir }}"
  register: eth_testnet_config_dir_register

- name: Copy configs
  when: not eth_testnet_config_dir_register.stat.exists
  block:
    - name: Use git
      ansible.builtin.import_tasks: copy_git.yaml
      when: eth_testnet_config_git_enabled

    - name: Use local
      ansible.builtin.import_tasks: copy_git.yaml
      when: eth_testnet_config_local_dir_enabled
